### PR TITLE
Add brackets to urls in doc comments to make them clickable

### PR DESCRIPTION
**Pull request by ZevEisenberg**
Adds angle brackets around all URLs in doc comments, which makes them clickable in Xcode's rendered documentation views. Also adds a lint rule to ensure that this style is maintained throughout the code base.

Note: the regex is slightly lazy in that does not look at the end of the URL. It's probably possible to make such a regex, but it might be ungainly enough that it's not worth it. Happy to take a crack at it if you think it's necessary.

Before:

A screenshot of some documentation rendered in Xcode's Quick Help Inspector. There is a URL, but it is not styled differently than the rest of the text.

After:

A screenshot of some documentation rendered in Xcode's Quick Help Inspector. There is a URL, and it is rendered in blue, indicating that it is clickable.

### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested.

### CODE REVIEW

**Comment by groue** [comment]
Thank you very much, @ZevEisenberg, this is a great contribution!

Kudos for the SwiftLint rule 👍

**Comment by groue** [comment]
Hello @ZevEisenberg,

It looks like the SwiftLint rule produces a lot of false positives. Do you know how to avoid them? I'm running SwiftLint 0.43.1.

Capture d’écran 2021-07-30 à 14 39 43

**Comment by ZevEisenberg** [comment]
oof, sorry about that. I'm not sure how I ended up convincing myself that the current regex works. I wasn't able to figure anything out quickly, but I'll look at it more a bit later. For now, I'd recommend disabling that rule if it's getting in the way.

**Comment by groue** [comment]
All right, @ZevEisenberg, thank you. I'm removing this rule until we find the proper regexp 👍

**Pull request merged**
