### PR TITLE
use #if directives to conditionally `@preconcurrency import `the `Dispatch` module to enable building the package on linux

### PR DESCRIPTION
**Pull request by tayloraswift**
see https://forums.swift.org/t/grdb-7-beta/75018/4

### Pull Request Checklist

- [x] CONTRIBUTING: You have read https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md
- [x] BRANCH: This pull request is submitted against the `development` branch.
- [x] DOCUMENTATION: Inline documentation has been updated.
- [x] DOCUMENTATION: README.md or another dedicated guide has been updated.
- [ ] TESTS: Changes are tested.
- [ ] TESTS: The `make smokeTest` terminal command runs without failure.

### CODE REVIEW

**Comment by groue** [comment]
Thank you @tayloraswift! Could you verify that these changes allow Swiftinit to build GRDB?

**Comment by tayloraswift** [comment]
yes, i was able to build my fork here: https://swiftinit.org/hist/tayloraswift.grdb.swift:enable-linux-build/grdb

**Comment by groue** [comment]
Thank you! This will ship in the next beta :-)

**Comment by groue** [comment]
⛵ Shipped in 7.0.0-beta.3

**Pull request merged**
