### PR TITLE
Add drop column support

### PR DESCRIPTION
**Pull request by TimAEllis**
Following on from #1138, This adds support for drop column. 

I did some poking and prodding with downloaded simulator versions and it would seem the first iOS version that shipped with >3.35 was iOS 15, was able to check against iOS 15.0 and iOS 14.5 (and those were the only simulator ranges available to download to check, i.e. couldn't check things like 14.6, 14.7 etc).

### Pull Request Checklist

- [x] CONTRIBUTING: You have read https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md
- [x] BRANCH: This pull request is submitted against the `development` branch.
- [x] DOCUMENTATION: Inline documentation has been updated.
- [x] DOCUMENTATION: README.md or another dedicated guide has been updated.
- [x] TESTS: Changes are tested.
- [x] TESTS: The `make smokeTest` terminal command runs without failure.

```
...
Executed 2279 tests, with 6 tests skipped and 0 failures (0 unexpected) in 87.346 (88.464) seconds
...
Executed 2279 tests, with 6 tests skipped and 0 failures (0 unexpected) in 93.532 (94.811) seconds
...
```

> The `make smokeTest` terminal command runs without failure.

_Sort of. I don't have simulators older than iOS 14.5 installed so it failed when trying to test against 13.7, otherwise it passed. If you are able to test against that specific version, that would be great as my tiny hard drive suffers with every simulator I download to it_

PS: Please be kind, I use this repository heaps and just wanted to help and not sure if I've missed anything in making this PR :)

### CODE REVIEW

**Comment by groue** [comment]
Hello @TimAEllis, this is great, thank you very much!

In order to complete the pull request, we just need to also expose `drop(column:)` to custom SQLite builds and SQLCipher. Those must not use availability checks. See the [implementation](https://github.com/groue/GRDB.swift/blob/v5.18.0/GRDB/QueryInterface/Schema/TableDefinition.swift#L739-L772) of `rename(column:to:)` for an example.

**Comment by groue** [comment]
> Sort of. I don't have simulators older than iOS 14.5 installed so it failed when trying to test against 13.7, otherwise it passed. If you are able to test against that specific version, that would be great as my tiny hard drive suffers with every simulator I download to it.

I will :-) It's high time I found a proper CI solution so that pull requests are properly checked. You did everything well 👍

**Comment by TimAEllis** [comment]
> Hello @TimAEllis, this is great, thank you very much!
> 
> In order to complete the pull request, we just need to also expose `drop(column:)` to custom SQLite builds and SQLCipher. Those must not use availability checks. See the [implementation](https://github.com/groue/GRDB.swift/blob/v5.18.0/GRDB/QueryInterface/Schema/TableDefinition.swift#L739-L772) of `rename(column:to:)` for an example.

This should be done with daf44d9baad443f985d93684d7bfa22cd717a83b

**Comment by groue** [comment]
Thank you @TimAEllis :-)

Reading the changes, I noticed that `TableDefinitionTests` would not always test that schema alterations would properly invalidate the internal GRDB schema cache. So I added tests for that, including one test for ALTER TABLE DROP COLUMN.

And... This test fails. Your changes are not responsible at all. This is an SQLite bug.

ALTER TABLE statements are supposed to call the [GRDB authorization callback](https://github.com/groue/GRDB.swift/blob/v5.18.0/GRDB/Core/StatementAuthorizer.swift#L36) with the [SQLITE_ALTER_TABLE](https://www.sqlite.org/c3ref/c_alter_table.html) code. This is how GRDB is able to [invalidate the schema cache](https://github.com/groue/GRDB.swift/blob/v5.18.0/GRDB/Core/StatementAuthorizer.swift#L65) whenever such a statement is run.

But ALTER TABLE DROP COLUMN does not trigger this behavior.

The consequence is that after a `drop(column: "foo")`, GRDB still thinks that `foo` is a column of the table, and this can create bugs later in the application.

Such bugs should be infrequent, since most apps perform schema changes early in their lifetime, before the GRDB schema cache had an opportunity to get warmed.

But I don't feel comfortable shipping a know bug. So the plans are:

1. Report the bug to the [SQLite forum](https://sqlite.org/forum/forummain)
2. Find a workaround

I can take care of (1). Do you want to take care of (2)?

**Comment by groue** [comment]
> 1. Report the bug to the [SQLite forum](https://sqlite.org/forum/forummain)

Reported as https://sqlite.org/forum/forumpost/bd47580ec2

**Comment by TimAEllis** [comment]
Hi @groue, this is starting to stretch my knowledge of SQLite (as little as it is, coming from MySQL). I mean, I'm happy to try and tackle this but I fear it won't be of acceptable quality 😅. I'm assuming I would have to hook into something like `TransactionObserver` but even that I literally only looked at for the first time today because of your reported message.

**Comment by groue** [comment]
All right @TimAEllis, I'll complete the PR :-)

**Comment by groue** [comment]
OK, looks good :-)

**Comment by groue** [comment]
Shipped in [v5.19.0](https://github.com/groue/GRDB.swift/tree/v5.19.0) 🚀

**Comment by groue** [comment]
> > 1. Report the bug to the [SQLite forum](https://sqlite.org/forum/forummain)
> 
> Reported as https://sqlite.org/forum/forumpost/bd47580ec2 (with the mention of a possible workaround).

[Fixed on trunk](https://sqlite.org/forum/forumpost/6537d092d020b387).

**Pull request merged**
