### PR TITLE
Added locking around `reducer` to mitigate Release build crashes.

### PR DESCRIPTION
**Pull request by mattgallagher**
This PR is related to https://github.com/groue/GRDB.swift/issues/1026

This PR demonstrates the workarounds we're using to avoid Release build crashes on an app project. The crashes appear to be around access and maintenance of the `reducer` property on `ValueObserver`.

I suggest broader consideration of the thread safety model around `reducer` before merging this PR as-is. There might be a more elegant way to do this.

### CODE REVIEW

**Review by Dark403969 — APPROVED** [review]

**Comment by groue** [comment]
Hello @mattgallagher,

I have audited the original code, and I could still not convince myself that the `reducer` property needs to be protected by a lock. It is always accessed from a serial dispatch queue (the "reducer queue", which computes the next published value after each impactful transaction), except when the initial value is fetched (and this happens before transactions become monitored, hence before the "reducer queue" can start doing anything).

So it looks like your PR fixes the crash in some indirect fashion. That's already quite an achievement :-)

My fear is that future changes to this file introduces this crash again. So I'll try to reproduce. #1026 does not give a clear recipe, but you gave enough hints.

I'll probably merge your pull request along with a detailed comment, so that we have a robust GRDB version, until I look further :-)

**Comment by mattgallagher** [comment]
@groue I agree that exactly why adding locks fixes the problem is not clear. The fact that this bug was triggered by a change in compiler indicates that it might be something very subtle.

I'll also try to reproduce the problem in a small (e.g. single file) example. I'll follow up when that's ready.

**Comment by groue** [comment]
I'm currently running this test in release configuration with Xcode 12.5.1 on an Intel iMac:

<details>
    <summary>code</summary>

```swift
class Issue1026Tests: XCTestCase {
    func testIssue1026() throws {
        let dbURL = try makeEmptyTempDirectory().appendingPathComponent("db.sqlite")
        let dbQueue = try DatabaseQueue(path: dbURL.path)
        try dbQueue.write { db in
            try db.execute(sql: """
                CREATE TABLE test (id INTEGER PRIMARY KEY)
                """)
        }
        
        let observation = ValueObservation
            .tracking { db in try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM test")! }
            .map { $0 }
            .removeDuplicates()
        
        let cancellable = observation.start(
            in: dbQueue,
            onError: { error in XCTFail("Unexpected error: \(error)") },
            onChange: {
                if $0 % 100 == 0 { print($0) }
            })
        
        for milliseconds in stride(from: 0, to: 100, by: 5) {
            print("\(milliseconds) milliseconds between two transactions")
            
            withExtendedLifetime(cancellable) {
                let expectation = self.expectation(description: "")
                let transactionCount = 5_000
                let delay = DispatchTimeInterval.milliseconds(milliseconds)
                
                var i = 0
                
                let timer = DispatchSource.makeTimerSource()
                timer.schedule(deadline: .now(), repeating: delay)
                timer.setEventHandler {
                    if i >= transactionCount {
                        expectation.fulfill()
                        timer.cancel()
                    }
                    
                    try! dbQueue.write { db in
                        try db.execute(sql: "INSERT INTO test DEFAULT VALUES")
                    }
                    
                    i += 1
                }
                timer.resume()
                
                waitForExpectations(timeout: .infinity, handler: nil)
            }
        }
    }
    
    /// Returns the URL of a new and unique temp directory. This directory is
    /// automatically deleted when the test method ends.
    func makeEmptyTempDirectory() throws -> URL {
        // Create a URL for an unique file in the system's temporary directory.
        let dirName = UUID().uuidString
        let dirURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(dirName)
        
        let fileManager = FileManager.default
        try fileManager.createDirectory(at: dirURL, withIntermediateDirectories: true, attributes: nil)
        
        // Add a teardown block to delete any file at `dirURL`.
        addTeardownBlock {
            do {
                let fileManager = FileManager.default
                // Check that the file exists before trying to delete it.
                if fileManager.fileExists(atPath: dirURL.path) {
                    // Perform the deletion.
                    try fileManager.removeItem(at: dirURL)
                    // Verify that the file no longer exists after the deletion.
                    XCTAssertFalse(fileManager.fileExists(atPath: dirURL.path))
                }
            } catch {
                // Treat any errors during file deletion as a test failure.
                XCTFail("Error while deleting temporary file: \(error)")
            }
        }
        
        // Return the temporary file URL for use in a test method.
        return dirURL
    }
}
```

</details>

Basically, it runs a lot of transactions at various intervals, and I hope it will eventually crash. I attempted at reproducing as much as I could for your initial report:

- The observation is a pipeline with `map` and `removeDuplicates`
- Interval between two transactions is around 50ms
- I write from some background thread in order to avoid the main queue from messing too much with the setup

It's very long to run, I'll report my findings.

**Comment by groue** [comment]
> I'll report my findings.

No crash :-/

I'm trying again, with slower reads this time

```swift
try dbQueue.write { db in
    try db.execute(sql: """
        CREATE TABLE test (id INTEGER PRIMARY KEY)
        """)
    
    db.add(function: DatabaseFunction("sleep", argumentCount: 0, pure: true) { _ in
        Thread.sleep(forTimeInterval: 0.05)
        return nil
    })
}

let observation = ValueObservation
    .tracking { db in try Int.fetchOne(db, sql: "SELECT COUNT(*), sleep() FROM test")! }
    .map { $0 }
    .removeDuplicates()
```

**Comment by groue** [comment]
> I'm trying again, with slower reads this time

Still no crash.

I'll have a less naive read of [your sentence](https://github.com/groue/GRDB.swift/issues/1026#issue-962276128):

> The timing is tricky. Produce transactions too fast and libdispatch is flooded (preventing the crash). Produce too slowly and there's not enough contention (avoiding the crash).

I suppose you're talking about contention of the database serial queue, which is busy performing this loop:

- write
- observation fetch
- write
- observation fetch
- etc

Those operations can not happen in a different order, because fetches won't happen unless a write was performed, and fetches are performed immediately right after writes, preventing any other write until the fetch is completed (concurrent reads only happen with DatabasePool and `ValueObservation.trackingConstantRegion`, and this is not our setup).

Contention happens when writes have to wait until the observation has finished fetching fresh values.

More precisely:

| time | operation | duration |
| ---- | --------- | -------- |
| t | write | w |
| t + w | fetch | f |
| t + interval | write | |

When `w + f` is greater than `interval`, contention starts.

According to your description, we want `w + f` to be very near `interval`, just at the edge of contention. That's what's I'm going to aim at in my next attempt.

**Comment by mattgallagher** [comment]
I'm currently trying to strip our project down to the database and relevant model files to see if I can produce the crash in a shareable example project. If you want to wait a few hours, it might be easier for me to reproduce this.

**Comment by groue** [comment]
I appreciate your help, @mattgallagher :-) We have all the time we need: whenever another user reports the same issue, I'll know how to help until the fix is shipped.

**Comment by groue** [comment]
No success so far attempting at triggering the crash by writing after a delay approximatively equal to the write + fetch duration, in order to err at the edge of contention :-/

**Comment by mattgallagher** [comment]
I've prepared the following app that demonstrates the problem. It reliably reproduces the bug in Xcode 12.5.1 running in the iOS 14.5 simulator on my MacBook Pro running macOS 11.5.

https://github.com/mattgallagher/GRDBValueObserverIssueApp

https://user-images.githubusercontent.com/28080/129446749-51a9cf95-20a6-48d7-89bb-c7353023ece5.mp4

**Comment by mattgallagher** [comment]
Here's the thread sanitiser reporting that the same `GRDB.ValueObservation<GRDB.ValueReducers.Trace<>>` is being accessed simultaneously from multiple threads.

```
WARNING: ThreadSanitizer: Swift access race (pid=59490)
  Modifying access of Swift variable at 0x7b100004e410 by thread T6:
    #0 closure #4 in ValueObservation.print(_:to:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b6670)
    #1 partial apply for closure #4 in ValueObservation.print(_:to:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b671f)
    #2 thunk for @escaping @callee_guaranteed () -> () <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b2d47)
    #3 partial apply for thunk for @escaping @callee_guaranteed () -> () <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bc321)
    #4 thunk for @escaping @callee_guaranteed () -> ()partial apply <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bd099)
    #5 thunk for @escaping @callee_guaranteed () -> ()partial apply <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bcfa8)
    #6 partial apply for thunk for @escaping @callee_guaranteed () -> (@out ()) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bc35b)
    #7 thunk for @escaping @callee_guaranteed () -> (@out ())partial apply <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bce33)
    #8 ValueObserver.databaseDidCommit(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bf14f)
    #9 protocol witness for TransactionObserver.databaseDidCommit(_:) in conformance ValueObserver<A> <null>:2 (GRDBValueObserverIssue:x86_64+0x1002c0009)
    #10 DatabaseObservationBroker.databaseDidCommit() <null>:2 (GRDBValueObserverIssue:x86_64+0x10014517d)
    #11 DatabaseObservationBroker.updateStatementDidExecute(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x10014433c)
    #12 Database.executeUpdateStatement(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x100061cdb)
    #13 UpdateStatement.execute(arguments:) <null>:2 (GRDBValueObserverIssue:x86_64+0x100117dc6)
    #14 Database.execute(literal:) <null>:2 (GRDBValueObserverIssue:x86_64+0x100061730)
    #15 Database.inTransaction(_:_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x10006eb9a)
    #16 closure #1 in DatabaseWriter.asyncWrite<A>(_:completion:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1000c59c5)
    #17 partial apply for closure #1 in DatabaseWriter.asyncWrite<A>(_:completion:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1000c5b91)
    #18 closure #1 in SerializedDatabase.async(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x100116453)
    #19 partial apply for closure #1 in SerializedDatabase.async(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x10011694f)
    #20 thunk for @escaping @callee_guaranteed () -> () <null>:2 (GRDBValueObserverIssue:x86_64+0x100087252)
    #21 __tsan::invoke_and_release_block(void*) <null>:2 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x7070b)
    #22 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x474d)

  Previous modifying access of Swift variable at 0x7b100004e410 by thread T3:
    #0 closure #5 in ValueObservation.print(_:to:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b6861)
    #1 partial apply for closure #5 in ValueObservation.print(_:to:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b695d)
    #2 thunk for @escaping @callee_guaranteed (@in_guaranteed A._ValueReducer.Value) -> () <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b4301)
    #3 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A._ValueReducer.Value) -> () <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bc830)
    #4 thunk for @escaping @callee_guaranteed (@in_guaranteed A._ValueReducer.Value) -> ()partial apply <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bd330)
    #5 thunk for @escaping @callee_guaranteed (@in_guaranteed A._ValueReducer.Value) -> (@out ()) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002b4371)
    #6 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A._ValueReducer.Value) -> (@out ()) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bc879)
    #7 ValueReducers.Trace._value(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002c4680)
    #8 protocol witness for _ValueReducer._value(_:) in conformance ValueReducers.Trace<A> <null>:2 (GRDBValueObserverIssue:x86_64+0x1002c47e9)
    #9 ValueReducers.RemoveDuplicates._value(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002c30b0)
    #10 protocol witness for _ValueReducer._value(_:) in conformance ValueReducers.RemoveDuplicates<A> <null>:2 (GRDBValueObserverIssue:x86_64+0x1002c33e9)
    #11 closure #2 in ValueObserver.databaseDidCommit(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002bfe8a)
    #12 partial apply for closure #2 in ValueObserver.databaseDidCommit(_:) <null>:2 (GRDBValueObserverIssue:x86_64+0x1002c0c7b)
    #13 thunk for @escaping @callee_guaranteed () -> () <null>:2 (GRDBValueObserverIssue:x86_64+0x100087252)
    #14 __tsan::invoke_and_release_block(void*) <null>:2 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x7070b)
    #15 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x474d)
```

**Comment by groue** [comment]
@mattgallagher, I can reproduce 🎉  And thanks for the thread sanitizer report as well.

Now I have something to chew on. Stay tuned!

**Comment by groue** [comment]
The thread sanitizer report had me [fix](https://github.com/groue/GRDB.swift/commit/adc16ea7dc887777f596aa0ca8fa7d6d0a9ece41) `ValueObservation.print()`, which would use its mutating `TextOutputStream` input in a thread-unsafe fashion.

Yet, our reducer crash is still there.

**Comment by groue** [comment]
OK. I merge your pull request. I forked your reproducing repository: you can discard it if you want.

**Comment by groue** [comment]
Shipped in [v5.9.0](https://github.com/groue/GRDB.swift/tree/v5.9.0).

**Pull request merged**
