### PR TITLE
Fix apple docs links

### PR DESCRIPTION
**Pull request by MartinP7r**
Just updating some links. I hope they're the correct ones. Please have a look yourself.

### Pull Request Checklist

- [x] CONTRIBUTING: You have read https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md
- [ ] BRANCH: This pull request is submitted against the `development` branch.
- [ ] DOCUMENTATION: Inline documentation has been updated.
- [x] DOCUMENTATION: README.md or another dedicated guide has been updated.
- [ ] TESTS: Changes are tested.
- [ ] TESTS: The `make smokeTest` terminal command runs without failure.

### CODE REVIEW

**Comment by groue** [comment]
Thank you very much @MartinP7r!

**Comment by groue** [comment]
(PRs should be submitted against the `development` branch)

**Comment by MartinP7r** [comment]
Thanks for changing the base branch. I paying attention.

**Comment by groue** [comment]
I wish the development branch would be the default target for pull requests, while master remains the default repository branch. This is a missing GitHub feature!

**Comment by MartinP7r** [comment]
That's true!  

Maybe something like this could be a workaround: https://github.com/marketplace/actions/check-base-branch

**Comment by groue** [comment]
Thank you very much for this hint!

**Pull request merged**
