### PR TITLE
Allow Swift static library integration via CocoaPods

### PR DESCRIPTION
**Pull request by chrisballinger**
### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested.

This PR resolves issue #360 which prevented using GRDB when integrated as a Swift static library via CocoaPods. It removes the custom modulemap and allows CocoaPods to generate the umbrella header with `grdb_config.h`. I successfully tested both the standard and SQLCipher subspecs against these changes.

If you'd like I could also remove the `use_frameworks!` line from the `README` as it would be no longer required if this were merged.

Cheers!

### CODE REVIEW

**Comment by groue** [comment]
Hi @chrisballinger,

This looks like a much useful PR. I'll look at it when I'm back from vacations, in about a week. Thank you very much for the investigation job which is behind :+1

**Comment by chrisballinger** [comment]
Thanks, no rush, enjoy your vacation!

**Comment by groue** [comment]
Suggestion:

> CocoaPods is a dependency manager for Xcode projects. To use GRDB with CocoaPods (version 1.2 or higher), specify in your Podfile:
>
> ```ruby
> pod 'GRDB.swift'
> ```
> 
> GRDB can be installed as a framework, or a static library.

**Comment by groue** [comment]
Oh, and also please merge in the latest development branch, and add your PR to the CHANGELOG: 570 goes right between 563 and 574. That'll nicely complete the PR :-)

**Comment by chrisballinger** [comment]
@groue Thanks for taking a look! You should be able to push to that branch now. I'll try to put the finishing touches on this PR tomorrow.

**Comment by groue** [comment]
> @groue Thanks for taking a look! You should be able to push to that branch now. I'll try to put the finishing touches on this PR tomorrow.

Push done! I hope Travis will swallow the new tests in the first stroke :-)

**Comment by chrisballinger** [comment]
@groue Rebased and added an entry to README and CHANGELOG

**Comment by groue** [comment]
Thank you @chrisballinger, welcome to the GRDB contributors!

I'd be happy to grant you push access to the repository. Drop me a line if you are interested!

**Pull request merged**
