### PR TITLE
QueryInterfaceRequest builder with dynamic table/view name

### PR DESCRIPTION
**Pull request by groue**
This pull request addresses #990, #916, and #833.

A new `Table` type is introduced, which can be used just as a `TableRecord` type. You can fetch, count, build requests, associations, etc.

```swift
// "Anonymous" Row table
let table = Table("player") // Or Table<Row>("player")
let count = try table.fetchCount(db)
let rows: [Row] = try table.fetchAll(db)
let rows: [Row] = try table.filter(...).fetchAll(db)
try table.deleteAll(db)
try table.deleteOne(db, key: 1)
try table.updateAll(db, ...)

// Typed table
struct Player: FetchableRecord { ... }
let table = Table<Player>("player")
let count = try table.fetchCount(db)
let players: [Player] = try table.fetchAll(db)
let players: [Player] = try table.filter(...).fetchAll(db)
try table.deleteAll(db)
try table.deleteOne(db, id: 1) // when Player is Identifiable
try table.updateAll(db, ...)
```

@Kirow, @forkdog, @sepw, @wzio, may I ask if this looks like it would address your initial feature request? See the [documentation diff](https://github.com/groue/GRDB.swift/pull/993/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

### CODE REVIEW

**Comment by sepw** [comment]
Hi @groue,

The addition of `Table("name")` looks like it would solve some of my requirements. In my current project I have several full text tables, all with the same schema: an ID and a text column. I currently use a generic table row type that allows the table name to be specified at compile time using generics. It looks like I will be able to replace this with your new `Table` type.

I took a brief look at the source for `Table` that adds an extension where `RowDecoder == Row`

```swift
extension Table where RowDecoder == Row {
     /// Create a `Table` of `Row`.
     ///
     ///     let table = Table("player") // Table<Row>
     public init(_ tableName: String) {
         self.init(tableName, Row.self)
     }
 }
```

This results in two `init(_ tableName: String)` initializers. Won't this cause call-site ambiguities?

**Comment by groue** [comment]
Thanks for your feedback, @sepw!

> Won't this cause call-site ambiguities?

None that I'm aware of. All snippets below compile fine:

```swift
struct Player: FetchableRecord { ... }

try dbQueue.read { db in
    do { let rows = try Table("player").fetchAll(db) }
    do { let rows: [Row] = try Table("player").fetchAll(db) }
    do { let rows = try Table("player").all().fetchAll(db) }
    do { let players = try Table<Player>("player").fetchAll(db) }
    do { let players = try Table<Player>("player").all().fetchAll(db) }
    do { let players: [Player] = try Table("player").fetchAll(db) }
    do { let players: [Player] = try Table("player").all().fetchAll(db) }
}
```

My goal with this default `Row` generic parameter is to make it possible to just declare a `Table` without qualifier when it would be inconvenient to choose a generic type. For example:

```swift
// We don't care about the actual generic parameter
let count = try Table("player").fetchCount(db)

// This avoids this kind of useless choice:
let count = try Table<Void>("player").fetchCount(db)   // ?
let count = try Table<Row>("player").fetchCount(db)    // ?
let count = try Table<Player>("player").fetchCount(db) // ?
let count = try Table<Never>("player").fetchCount(db)  // ?
let count = try Table<WHAT>("player").fetchCount(db)   // ?
```

The same pattern is already used for [Common Table Expressions](https://github.com/groue/GRDB.swift/blob/master/Documentation/CommonTableExpressions.md), and `SQLRequest`, without known downside:

```swift
// SELECT * FROM player WHERE score = (SELECT MAX(score) FROM player)
let subquery = SQLRequest("SELECT MAX(score) FROM player") // Implicit SQLRequest<Row>
let request = SQLRequest<Player>("SELECT * FROM player WHERE score = (\(subquery))")
let players = try request.fetchAll(db) // [Player]
```

I know it's an uncommon API pattern - and a rather hidden one. Not everybody will use it, or will be conscious of its existence. But I've too frequently seen myself inject arbitrary types just to make the compiler happy. Defaulting to `Row` seemed like a better option, it does not look like it hurts anybody, and I decided the experiment was worth it.

**Comment by groue** [comment]
Note to self: add deletion methods (`table.deleteAll(_:)`, `.delete(_:id:)`, etc.), and batch updates as well.

**Comment by sepw** [comment]
@groue, thank you for the explanation of the initializer with the `RowDecoder == Row` predicate. I wasn’t aware that this technique could be used to simulated default generic arguments. Very useful!

**Comment by groue** [comment]
Yep! The pattern is:

```swift
struct Foo<T> {
    // Support
    private init(_ type: T.Type) { }
    
    // Initializer for explicit generic parameter
    init() {
        self.init(T.self)
    }
}

extension Foo where T == Default {
    // Initializer for default generic parameter
    init() {
        self.init(Default.self)
    }
}

// Explicit generic parameter
let foo = Foo<Int>() 

// Default generic parameter
let foo = Foo()
```

**Comment by groue** [comment]
😠 Travis is dead

**Comment by NewestUser** [comment]
Is it possible to insert data using the `Table` struct? Or even better perform a `save` like in `MutablePersistableRecord` without actually caring of the mutation result?

PS: Awesome lib, thanks!

**Comment by groue** [comment]
Hello @NewestUser, `Table` does not provide any saving features. If you want this topic to be explored, please explain your use case (don't say _how_ you want to do something, instead focus on _what_ you want to do).

**Comment by NewestUser** [comment]
Thanks for the reply.

I have an iOS app that supports multiple languages. Each language has it's own set of tables containing data specific for each language.
Example. `table1_bg`, `table2_bg`, `table1_en`, `table2_en`, `table1_de`, `table2_de` etc...
`table1_bg`, `table1_en` and `table1_de` all have the same schema. They differ only by the data stored in those tables and the name suffix of the table.

Depending on the language that the application is running in the appropriate table suffix will be used.

A natural response to this design decision that I have made might be: _You can add a new language column in each of the tables and add an extra where clause to your queries so that only data for the particular language is selected._

This is true, however the effort that I needed to spent in order to do this was far more than just adjusting table suffixes.
Keeping data in separate tables with the same schemas allowed me to:
- Easily add new languages without having to adapt existing repository layer. Otherwise I would have to do a DB migration that would involve creating the new tables with the extra language column, copy data from old tables into the new ones and then clearing out the old tables. Keep in mind that these kind of migrations are done on mobile devices that are outside of your control. Sometimes one needs to keep these migration in mind for months when developing the app. The reason being is that it takes months for users to upgrade to the latest version of the app. Especially when you have a large user base. So introducing backwards incompatible changes on a db level can happen. This always leads to increased uninstall rates and user loss.
- Keep the size of tables and indices low since each language has ~10k of records.

PS: Merry Christmas 🎄

**Comment by groue** [comment]
> [...] however the effort that I needed to spent in order to do this was far more compared to just adjusting table suffixes.

Is it?

**Comment by NewestUser** [comment]
If you account for the db migration that would last months I would say yet it was.
Either way I am not defending the design decision that I made. If I was to implement a server side db model I would never go this route. However the current state is that I have different tables with the same schema for different languages. In addition this db schema is shared by an android app and as a single developer supporting both platforms it is easier for me to keep thinks as close as possible.

For what reason `Table` does not provide saving features? Would it require restructuring a huge chunk of the code base or something else?

**Comment by groue** [comment]
> PS: Merry Christmas 🎄

You too :-) Happy New Year's Eve!

> If you account for the db migration that would last months I would say yes it is.

We still miss the rationale that supports such a claim. Don't worry, I guess it is about your Android app, and I can understand that.

> For what reason `Table` does not provide saving features?

No good reason. The popular request was the ability to build SELECT queries. I agree that the current state of the `Table` struct, able to build requests, but unable to perform inserts, is problematic. It is not cool to take a road, drive for a while, and discover later that it is a dead-end.

> Would it require restructuring a huge chunk of the code base or something else?

I don't think so. We'd just need to design an API and implement it. I would welcome such a contribution, since it would fill a hole in the api.

Now my recommendation is still the same: **stick to the standard relational model**. Leaving it is begging for trouble. You just met one (because database libraries do not spend much energy helping unorthodox practices) - you are likely to meet other ones (because opting out of the relational model is exposing yourself to the troubles it is designed to avoid).

**Pull request merged**
