### PR TITLE
GRDB 6

### PR DESCRIPTION
**Pull request by groue**
GRDB 6, the next major version of GRDB.

### CODE REVIEW

**Comment by mallman** [comment]
Ooooo... the GRDB 6 WIP... how tantalizing! Is there a roadmap? As a heavy-duty, industrial-strength consumer of GRDB perhaps I can offer feedback based on my experience?

**Comment by groue** [comment]
Hello @mallman,

There are already a few items in the CHANGELOG, but I'd like to ship or at least pave the way for:

- Bump Swift and Xcode requirements to the latest
- Universal coding/decoding errors (no more fatal errors when the database is not trusted)
- UPSERT and RETURNING
- More JSON

ETA is WWDC.

**Comment by groue** [comment]
> ETA is WWDC.

The fool of me ;-) The ETA is the release of Xcode 14.

**Comment by groue** [comment]
Looks like we're ready for a beta release :-)

**Pull request merged**
