### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by zmeyc**

### CODE REVIEW

**Comment by groue** [comment]
Hello @zmeyc, I'm glad to hear from you!

I'll look into this PR very shortly.

**Comment by zmeyc** [comment]
Thanks!
I accidentally added Linux support to the same PR branch, will fix this in a few hours.

**Comment by groue** [comment]
OK, we'll talk about all those `#if os(Linux)` later. Sounds good to me.

**Comment by zmeyc** [comment]
https://github.com/groue/GRDB.swift/pull/202

**Pull request closed without merging**
