### PR TITLE
Eager Loading of HasMany associations

### PR DESCRIPTION
**Pull request by groue**
This PR "completes" the associations feature set by allowing eager loading of HasMany and HasManyThrough associations:

```swift
// Setup
struct Author: TableRecord, FetchableRecord, Decodable {
    static let books = hasMany(Book.self)
    var id: Int64
    var name: String
}

struct Book: TableRecord, FetchableRecord, Decodable {
    var id: Int64
    var authorId: Int64
    var title: String
}

// Load all authors along with their books
struct AuthorInfo: FetchableRecord, Decodable {
    var author: Author
    var books: [Book]
}

let request = Author.including(all: Author.books)
let infos: [AuthorInfo] = try AuthorInfo.fetchAll(db, request)

for info in infos {
    print("\(info.author.name) wrote:")
    for book in info.books {
        print("- \(book.title)")
    }
}
```

### CODE REVIEW

**Comment by zdnk** [comment]
Nice! How to use it with `init(row: Row)`?

**Comment by groue** [comment]
> How to use it with init(row: Row)?

You mean, without Decodable?

Currently:

```swift
struct Author: FetchableRecord {
    var books: [Book]
    init(row: Row) {
        self.books = row.prefetches["books"].map(Book.init(row:))
    }
}
```

Soon (will be rock stable):

```swift
struct Author {
    var books: [Book]
    init(row: Row) {
        self.books = row["books"]
    }
}
```

You can use this draft PR, but mind that API is still *very unstable*. I may rename the Row `prefetches` property eventually. The keys will often be off: you may have to access associated records with a singular ("book") key instead of the plural ("books"). Or the opposite. Some commits in this branch may break things.

Until the final merge :-)

**Comment by zdnk** [comment]
Yep, thats what I thought.

What about nested eager loading? Let's say I have A which hasOne B and B hasMany of C. And I would like to load complete A with B and all its Cs in single request.

**Comment by groue** [comment]
Nested eager loading is supported. Any numbers of levels of inclusions of to-one or to-many associations. Not all cases have been tested yet, though ;-)

**Comment by groue** [comment]
> Let's say I have A which hasOne B and B hasMany of C. And I would like to load complete A with B and all its Cs in single request.

You can:

```swift
extension A {
    static let b = hasOne(B.self)
}
extension B {
    static let cs = hasMany(C.self)
}

let request = A.including(required: A.b.including(all: B.cs)

// Can decode a "flat" record:
struct AInfo1: FetchableRecord {
    var a: A
    var b: B
    var cs: [C]

    init(row: Row) {
        self.a = A(row: row)
        self.b = row["b"]
        self.cs = row.prefetches["cs"].map(C.init(row:))
    }
}

// Can also decode a "nested" record:
struct AInfo2: FetchableRecord {
    struct BInfo: FetchableRecord {
        var b: B
        var cs: [C]
        init(row: Row) {
            self.b = A(row: row)
            self.cs = row.prefetches["cs"].map(C.init(row:))
        }
    }

    var a: A
    var bInfo: BInfo

    init(row: Row) {
        self.a = A(row: row)
        self.b = row["b"]
    }
}
```

GRDB 4 also introduces the [HasManyThrough](https://github.com/groue/GRDB.swift/blob/GRDB-4.0/Documentation/AssociationsBasics.md#hasmanythrough) association. "A has many C through B".

```swift
extension A {
    static let cs = hasMany(C.self, through: A.b, via: B.cs)
}
```

Those indirect associations can also be eager-loaded, skipping the intermediate records:

```swift
let request = A.including(all: A.cs)
```

**Comment by groue** [comment]
@zdnk, if you still don't want to use Decodable, row subscripts are now ready:

```swift
// Setup
struct Author: TableRecord, FetchableRecord {
    static let books = hasMany(Book.self)
    var id: Int64
    var name: String
}

struct Book: TableRecord, FetchableRecord {
    var id: Int64
    var authorId: Int64
    var title: String
}

// Load all authors along with their books
struct AuthorInfo: FetchableRecord {
    var author: Author
    var books: [Book]

    init(row: Row) {
        author = Author(row: row)
        books = row["books"] // <--- subscript
    }
}

let request = Author.including(all: Author.books)
let infos: [AuthorInfo] = try AuthorInfo.fetchAll(db, request)
```

> Let's say I have A which hasOne B and B hasMany of C. And I would like to load complete A with B and all its Cs in single request.

```swift
extension A: TableRecord, FetchableRecord {
    static let b = hasOne(B.self)
}
extension B: TableRecord, FetchableRecord {
    static let cs = hasMany(C.self)
}

struct AInfo: FetchableRecord {
    var a: A
    var b: B
    var cs: [C]
    init(row: Row) {
        self.a = A(row: row)
        self.b = row["b"]
        self.cs = row["cs"] // <--- subscript (can look up nested associations)
    }
}

let request = A.including(required: A.b.including(all: B.cs)
let infos: [AInfo] = try AInfo.fetchAll(db, request)
```

**Comment by groue** [comment]
Implementation complete 🎉 

Now we need a big documentation update 😅

**Pull request merged**
