### PR TITLE
Add support for tvOS

### PR DESCRIPTION
**Pull request by kdubb**
## Xcode Project
- [x] tvOS Target
- [x] tvOS Unit Test Target
- [x] tvOS Scheme

## Makefile
- [x] tvOS Target Min/Max
- [x] tvOS Actions (copies iOS)

## CI
- [x] tvOS Travis stages

## Packaging
- [x] CocoaPods - Podfile Updated
- [x] ~SwiftPM - Not Changes Required~

## Documentation
- [x] Readme Updated

### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested.

### CODE REVIEW

**Comment by groue** [comment]
Hello @kdubb,

Thanks for this pull request of high quality! It looks like it should be merged in shortly.

One Travis check has failed, though. When I run `make test_framework_GRDBtvOS_minTarget` with Xcode 10.2.1 on my machine, I get the following output:

> xctest (82461) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “GRDBtvOSTests” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. 

Are we sure tvOS 9.0 is testable?

**Comment by kdubb** [comment]
@groue Truth be told I didn't run it against tvOS 9.0 locally; I was relying on Travis to test permutations.

I cannot get tvOS 9.0 to run either so I bumped the minimum to 10.0

**Comment by groue** [comment]
That's what Travis is for :-)

Thank you very much @kdubb. Hey, this is your second merged pull request here, after #160. Would you like a push access to the repository? Just drop me a line, and I'll invite you.

**Comment by groue** [comment]
Shipped in v4.3.0

**Pull request merged**
