### PR TITLE
Working xcode10/Swift 4.2 build

### PR DESCRIPTION
**Pull request by QuestofIranon**
this brings the branch up to date and building with xcode10/swift 4.2 per #379

### CODE REVIEW

**Comment by groue** [comment]
Hello again @QuestofIranon, thanks for your pull request.

It won't be accepted.

Requiring Swift 4.2 and Xcode 10 is a **breaking change**, which means that we'd have to bump GRDB to version 4. But Xcode has a compatibility mode that lets it compile Swift 4.1: we can thus preserve the Swift 4.1+ / Xcode 9.3+ requirement even after Xcode 10 has shipped. For more information, ask Google about the advantages of semantic versioning (the first one is that people are happier when things that don't have to break don't break).

For your next pull request, please ask beforehand if the direction you aim at has a chance of being merged in. For example, why didn't you answer in #379? Engage conversation.

Last advice: don't ignore the [pull request template](https://raw.githubusercontent.com/groue/GRDB.swift/master/.github/PULL_REQUEST_TEMPLATE.md) when you submit one.

See you soon, if you are in a mood for preparing Xcode 10 release.

**Comment by QuestofIranon** [comment]
What is the purpose of your Swift4.2 branch if not to prepare for the XCode 10 launch?

**Comment by groue** [comment]
It is a branch for experimenting with Xcode 10. It has been created in a time I didn't know much yet about this Xcode release. It's a private branch of mine, if you want. I may trash it. Or not.

GRDB does make promises that you can rely on, and those are all expressed in the README of the master branch.

There is another promise, non-written, which is that there is always a stable version of GRDB that runs with the latest stable version of Xcode. More precisely, count a few days after Xcode has shipped for GRDB to be upgraded if necessary. You will be able to run GRDB with Xcode 10 after it has officially shipped.

There is a promise I don't make, which is that beta software gets the same level of support than stable software. When you run beta, you may be lucky, and get some help (as you had in #379). But you may also be left alone fixing your issue. Running beta is risky.

And everything else is wild speculation ;-)

My turn to ask a question: why didn't you simply follow my advice in #379?

**Comment by QuestofIranon** [comment]
I did take your advice
> Unless you are willing to contribute, I recommend that you step back:

**Comment by groue** [comment]
Good. So there is nothing left that needs to be solved.

**Pull request closed without merging**
