### PR TITLE
Add Travis-CI build status badge to README.md

### PR DESCRIPTION
**Pull request by swiftlyfalling**
(Travis seems to have a bit of a backlog right now running osx builds, but all this changes is the README.md)

NOTE: If merging, add `[ci skip]` (no quotes or special formatting needed) to the commit message to skip a fresh Travis-CI build for simple documentation / readme changes.

### CODE REVIEW

**Comment by swiftlyfalling** [comment]
@groue: The error that occurred in test run 5.16 is an intermittent error I've seen running the test suites - there may be a race condition in the test itself:

```swift
GRDBCipheriOSEncryptedTests.DatabaseQueueuReleaseMemoryTests
  testDatabaseIteratorRetainConnectionAndReturnError:, XCTAssertTrue failed - 
  /Users/travis/build/groue/GRDB.swift/Tests/GRDBTests/DatabaseQueueReleaseMemoryTests.swift:171
    >
    >                cursor = nil
    >                XCTAssertTrue(connection == nil)
    >            }
    >
```

Re-running the test is likely to succeed. (It's unrelated to this PR.)

**Comment by groue** [comment]
Hello @swiftlyfalling! I'm not sure I want to merge this PR.

A flaky test (like #216) or a travis hiccup would put a very negative red flag on the home page. A red flag that says nothing about the severity of the problem. A red flag that does not distinguish between bugs in the test suite, and bugs in the library.

I greatly appreciate the quality of your Travis setup. It's so very clear that you *care*. And now we have a great safety belt, and a great time saver. But CI is a development tool, not a communication tool: we don't have to *show* that GRDB has CI. 

Not displaying the badge is not a matter of opacity: it's a matter of avoiding something that has little value, and yet a big impact on our agenda (should the badge turn red).

What do you think?

> NOTE: If merging, add [ci skip] (no quotes or special formatting needed) to the commit message to skip a fresh Travis-CI build for simple documentation / readme changes.

That's interesting. Some repositories wait for a "please smoke tests" comment.

**Comment by swiftlyfalling** [comment]
@groue: Yeah - there's certainly a bit of a catch-22 with the CI badge. Of course, the ideal is to have perfectly stable tests (and CI runs) that are 100% "correct" and provide full coverage... and, thus, a CI error is a sure sign of a problem that needs to be fixed. The badge itself can tell you none of this (although a click through takes you to the details) - nor that a "pass" actually means all the important things are tested.

I think there are some folks who look for the presence of the badge (which is fairly popular among open-source repos) as a positive indicator of the importance of testing to the project.

I'm absolutely not married to the badge itself - but I do think that some additional information about how well-tested GRDB is (in addition to the short "Well documented & tested" mention) might be worthwhile, to help encourage those who stop by (and are looking for that info) to consider using GRDB. The fact that it has such an expansive suite of tests, and has constant testing of all the combinations, is something that should be highlighted, IMHO.

**Comment by groue** [comment]
I hear your arguments. I'll try to fix #216 first.

**Comment by groue** [comment]
Thanks @swiftlyfalling!

**Pull request merged**
