### PR TITLE
Add cache for TableRecord.defaultDatabaseTableName

### LINKED ISSUE #637: defaultDatabaseTableName should be cached
We have noticed a fairly big cpu and memory impact when inserting/updating many items from repeated calls to `TableRecord.defaultDatabaseTableName` (because of the regex calls). This should be easily cacheable. I'm sorry, I don't have time to send a Pull Request 🙁

### PR DESCRIPTION
**Pull request by gjeck**
Resolves #637. Reduces cpu/memory impact from repeated calls to `TableRecord.defaultDatabaseTableName` by cacheing the name in a private global NSCache.

### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested.

### CODE REVIEW

**Comment by groue** [comment]
That's lovely, @gjeck 👍 

Did you run some benchmarks and see any difference?

**Comment by gjeck** [comment]
I wasn't sure if it was worth committing but I did write a very basic performance test that potentially demonstrated the improvement. This was the test:
```
class TableRecordPerformanceTests: XCTestCase {
    func testPerformanceExample() {
        self.measure {
            (0...10000).forEach { _ in
                _ = MockRecord.databaseTableName
            }
        }
    }
}
private struct MockRecord: TableRecord {}
```

This was the result before adding the cache:
```
Test Case '-[GRDBOSXPerformanceTests.TableRecordPerformanceTests testPerformanceExample]' measured [Time, seconds] average: 0.148, relative standard deviation: 4.136%, values: [0.165622, 0.147685, 0.146469, 0.145622, 0.146661, 0.147595, 0.149581, 0.142303, 0.146900, 0.143601], performanceMetricID:com.apple.XCTPerformanceMetric_WallClockTime, baselineName: "", baselineAverage: , maxPercentRegression: 10.000%, maxPercentRelativeStandardDeviation: 10.000%, maxRegression: 0.100, maxStandardDeviation: 0.100
```

This was the result after adding the cache:
```
Test Case '-[GRDBOSXPerformanceTests.TableRecordPerformanceTests testPerformanceExample]' measured [Time, seconds] average: 0.022, relative standard deviation: 10.138%, values: [0.028496, 0.021501, 0.020826, 0.021478, 0.022193, 0.019994, 0.021537, 0.021261, 0.021149, 0.021637], performanceMetricID:com.apple.XCTPerformanceMetric_WallClockTime, baselineName: "", baselineAverage: , maxPercentRegression: 10.000%, maxPercentRelativeStandardDeviation: 10.000%, maxRegression: 0.100, maxStandardDeviation: 0.100
```

So not an earth shattering improvement, but the average case seems quite a bit better (0.148 vs 0.022).

**Comment by groue** [comment]
That's still an improvement!

**Comment by groue** [comment]
Welcome in, @gjeck 🤗 Would you like to be granted a push access to the repository? I'll invite you right away.

**Comment by gjeck** [comment]
Sweet! Yeah that would be awesome, thank you 😄

**Comment by groue** [comment]
Shipped in v4.9.0 :-)

**Pull request merged**
