### PR TITLE
Expose reading errors

### PR DESCRIPTION
**Pull request by groue**
This pull request addresses #147 and changes GRDB so that it exposes reading errors.

Until now, GRDB would assume that both SQLite and the database file(s) were fundamentally trustable. Well, the file system is not trustable. Applications have to be able to deal with I/O errors.

The fetching methods have thus been updated:

```diff
-Type.fetch(...) -> DatabaseSequence<Type>
-Type.fetchAll(...) -> [Type]
-Type.fetchOne(...) -> Type?
+Type.fetchCursor(...) throws -> DatabaseCursor<Type>
+Type.fetchAll(...) throws -> [Type]
+Type.fetchOne(...) throws -> Type?
```

Usage:

```swift
// Fetch cursors
let rows = try Row.fetchCursor(db, ...) // DatabaseCursor<Row>
while let row = try rows.next() { ... } // Row

// Fetch arrays
let rows = try Row.fetchAll(db, ...)    // [Row]

// Fetch individual values:
let row = try Row.fetchOne(db, ...)     // Row?
```

### CODE REVIEW

**Comment by groue** [comment]
Remaining TODO:

- FetchedRecordsController error handling
- Documentation update

**Comment by swiftlyfalling** [comment]
@groue: These changes are fantastic! Having the easy ability to catch and handle these sort of errors gracefully (and non-fatally) is ***greatly*** appreciated. 🎉

A quick question:

- `DatabaseStore.setFileAttributes(...)` still has two uses of `try!`, and it would seem to me that this would be another candidate for re-throwing the error? Certainly, it seems as though the first call to `setFileAttributes` in `DatabaseStore.init(...)` could easily expose any thrown error. What to do inside the DispatchSource's eventHandler is a bit less obvious, I suppose - but crashing in a DispatchSource event handler (if the call inside `setFileAttributes` fails) is probably non-ideal (as the cause is likely an external filesystem / system event).

**Comment by groue** [comment]
@swiftlyfalling Thanks for your support!

> A quick question: [...] `DatabaseStore.setFileAttributes` [...] What to do inside the DispatchSource's eventHandler is a bit less obvious, I suppose.

You bet! Those `try!` itch a lot, and I still don't know yet how to handle those callback errors.

Facts:

1. Configuration.fileAttributes and DatabaseStore were introduced in order to support [File Protection modes](https://developer.apple.com/reference/foundation/filemanager/1653059-file_protection_values).

2. [Tests for file attributes](https://github.com/groue/GRDB.swift/blob/adc4ae48d6998886cd5106e9a93ecfd704533661/Tests/Public/Core/DatabasePool/DatabasePoolFileAttributesTests.swift#L71-L72) are fragile, and fail once in a while.

3. I once read, but can't Google for evidence any longer, that starting from some version of iOS, a directory's NSFileProtectionKey is inherited by its contained files. This "fact" cruelly lacks precision :persevere:

4. sqlite3.h that ships with macOS/iOS contains those undocumented database opening flags:

    ```c
    #define SQLITE_OPEN_FILEPROTECTION_COMPLETE                             0x00100000
    #define SQLITE_OPEN_FILEPROTECTION_COMPLETEUNLESSOPEN                   0x00200000
    #define SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION 0x00300000
    #define SQLITE_OPEN_FILEPROTECTION_NONE                                 0x00400000
    #define SQLITE_OPEN_FILEPROTECTION_MASK                                 0x00700000
    ```
    
    Those flags are not present in the sqlite3.h generated by [SQLCipher](https://github.com/sqlcipher/sqlcipher) or [SQLiteLib](http://github.com/swiftlyfalling/SQLiteLib). If thus guess that Apple has modified SQLite in order to bake file protection modes right in.

This makes me think that there's a lot to be done about NSFileProtectionKey!

**Comment by groue** [comment]
Fortunately, I'm currently developing an iOS app that needs two databases with different file protection modes - I'll be able to dig deeper in the subject.

**Comment by groue** [comment]
@kdubb, @swiftlyfalling This PR looks ready.

Errors from FetchedRecordsController and DatabaseStorage are not handled yet, but this is not a regression: we can deal with those errors in future PRs. I encourage you to check out the [DatabaseCursor branch](https://github.com/groue/GRDB.swift/tree/DatabaseCursor) and evaluate this new version.

See:
- [CHANGELOG](https://github.com/groue/GRDB.swift/blob/DatabaseCursor/CHANGELOG.md)
- [Updated documentation for Fetching Methods](https://github.com/groue/GRDB.swift/blob/DatabaseCursor/README.md#fetching-methods)
- [Updated documentation for Error Handling](https://github.com/groue/GRDB.swift/blob/DatabaseCursor/README.md#error-handling)

**Comment by groue** [comment]
All right, folks! GRDB v0.91.0 has shipped :-) Thanks again @kdubb for the kick!

**Comment by groue** [comment]
@kdubb @swiftlyfalling I'm currently writing an app that needs to properly handle database errors on a [locked device](https://developer.apple.com/reference/foundation/fileattributekey/1616632-protectionkey). I can not tell you how much GRDB owes to you ❤️

**Comment by swiftlyfalling** [comment]
@groue: Yes, that's (unfortunately) an all-too-frequent issue if one wants to support background execution & Data Protection on an iOS device.

These changes are fantastic and make it all possible. 🎉

**Pull request merged**
