### PR TITLE
Minor typo fix

### PR DESCRIPTION
**Pull request by bellebethcooper**
Just a minor typo fix in documentation.

### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested.

### CODE REVIEW

**Comment by groue** [comment]
Hey, thank you very much @bellebethcooper 👍 

Did I already invite you as a collaborator to the repo, so that you have push access? If not, and if you are interested, just drop me a line.

**Comment by bellebethcooper** [comment]
No problem! Nice to be able to help in small ways :) I don't think I have push access, no. If you're happy to do that, it'd make these little edits quicker :)

Thanks as always for your work on GRDB! I'm using it right now for a new app using SwiftUI and Combine, and I've just discovered GRDBCombine which I'm excited to start looking at.

**Comment by groue** [comment]
It'll be a pleasure to count you in! 💯 

And thanks for giving GRDBCombine a try, that's really cool! It's very young, but it *should* work: please open an issue if anything looks weird. Also, I don't have any professional use for it right now, so I could not really check its ability at fulfilling our daily needs: feel free to comment on any pain point you could meet as well :-) Much of it is inspired from RxGRDB - some missing context or information may be available [there](https://github.com/RxSwiftCommunity/RxGRDB/blob/master/README.md).

**Comment by bellebethcooper** [comment]
Perfect, thanks! I've been exclusively using `PromiseKit` so anything reactive outside promises is all new to me. I've been leaning heavily on `RxSwift` docs to get my head around it all, so I'll definitely read up on `RxGRDB` as well :)

**Comment by groue** [comment]
Looks like a smart move. I'm happy I've been introduced to RxSwift before Combine was shipped. It's much easier to grok it after a little practice has lifted the darkest shadows.

**Comment by bellebethcooper** [comment]
I believe that! I'm glad I started with PromiseKit, as I found that hard to wrap my head around at first, but it's been a good base for picking up Combine.

**Comment by groue** [comment]
Fun times :-)

**Pull request merged**
