### PR TITLE
Getting carthage tests to pass

### PR DESCRIPTION
**Pull request by KyleLeneau**
This MR updates the test project used for Carthage testing. I have run the make command and have been seeing some good success now.

### One more thing…

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested, for all flavors of GRDB, GRDBCipher, and GRDBCustomSQLite.
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by groue** [comment]
Hello @KyleLeneau, thanks for chiming in! 

It looks like Travis tests do not pass. Also, your PR brings several changes which look unrelated to Carthage.

If you wish to continue, please:

- Use Xcode 10, and don't change Swift version in projects unless needed (and please explain).
- Look at #262. "Seeing some good success" is likely not enough. The problem is that Carthage does not build frameworks in a reproducible way: you'll witness *differences* between two Carthage builds, and those differences *may* explain why Carthage builds *sometimes* fail.

I will accept a Carthage pull request if and only if one of those two conditions is met:

1. Carthage builds are 100% reliable.
2. Someone is ready to provide long-term support for Carthage-related issues in GRDB. This is quite an involvement.

The underlying problem is that supporting Carthage-related issues (including providing you guidance in this PR) is a time sink that I can not, personally, afford.

**Comment by KyleLeneau** [comment]
Hey @groue, Thanks for the feedback. I made some changes like you said. One of the obvious issues I found was with the test target, I had to update/lock the swift version to 4.2 which allowed me to rollback the containment API change.

As for your other comments, let me see how the next CI goes. Carthage support is not that odd and since you have a nice workspace setup that can build than that's all Carthage needs. I will explore a bit more why we might see un-explainable errors.

**Comment by groue** [comment]
Thanks @KyleLeneau,

Travis is happy again, and you have restored Carthage tests. 👍 

If you feel happy with this state of the PR, here is my suggestion: keep everything but restore README.md in its original state. We'll then have the best setup I could dream of:

- a `make test_CarthageBuild` that passes
- Travis running Carthage tests on every branch & pull request

This will give your PR the opportunity to run Carthage tests many times. Your contribution is not lost. You made what is needed for Carthage to remain available in the long run. And in the same time, as I see Carthage builds succeed, one after the others, I'll eventually become confident enough. I'll then make README.md less cautious, and publicly support Carthage (which means dedicate time helping users solve their Carthage issues).

Is this OK for you?

**Comment by KyleLeneau** [comment]
Hey @groue,

I am happy with your suggestion. I reverted the README changes like you suggested and see another passed build. Go ahead and merge this when you are comfortable. I am happy to continue to help out how I can should issues come up.

Thanks,
Kyle

**Comment by groue** [comment]
That's great, @KyleLeneau. Thanks for pushing this topic forward :-)

**Comment by KyleLeneau** [comment]
Hey @groue, yeah I would be happy to have that incase something urgent comes up.

**Comment by groue** [comment]
You're welcome!

**Pull request merged**
