### PR TITLE
Allow query planner to optimize some boolean tests

### PR DESCRIPTION
**Pull request by groue**
This pull request changes the SQL generated by boolean tests:

```swift
// GRDB 4: SELECT * FROM player WHERE isActive
// GRDB 5: SELECT * FROM player WHERE isActive = 1
Player.filter(Column("isActive") == true)

// GRDB 4: SELECT * FROM player WHERE NOT isActive
// GRDB 5: SELECT * FROM player WHERE isActive = 0
Player.filter(Column("isActive") == false)

// GRDB 4 & 5: SELECT * FROM player WHERE isActive
Player.filter(Column("isActive"))

// GRDB 4 & 5: SELECT * FROM player WHERE NOT isActive
Player.filter(!Column("isActive"))
```

The goal is allow users to trigger SQLite query planner optimizations when boolean columns and expressions are indexed (see #816 for the feature request).

However, this change is breaking for database boolean values that are not `0`, `1`, or `NULL`.

### CODE REVIEW

**Comment by groue** [comment]
@mallman, do we agree this is what you had in mind?

**Comment by groue** [comment]
> @mallman, do we agree this is what you had in mind?

Precisely speaking, *all* explicit Boolean checks are now fully expressed in SQL, with the sole exception of the `isEmpty` aggregate:

```swift
// SELECT ... HAVING COUNT(player.id) > 0
Team.having(Team.players.isEmpty == false)

// SELECT ... HAVING COUNT(player.id) = 0
Team.having(Team.players.isEmpty == true)

// SELECT ... HAVING COUNT(player.id) = 0
Team.having(Team.players.isEmpty)
```

**Comment by mallman** [comment]
Looks good to me. I'm especially impressed by the support for indexed expressions. I didn't know SQLite supported that feature.

Thank you @groue!

**Comment by groue** [comment]
You're welcome! Yeah, I sometimes check the SQLite release notes, so I learn about one trick or two ;-) Next beta will ship shortly. Thanks for having improved the library for you and other demanding users. And thanks for submitting your request while it was possible to introduce a breaking change 👍

**Comment by groue** [comment]
Shipped in beta 10!

**Pull request merged**
