### PR TITLE
Support BUILD_LIBRARY_FOR_DISTRIBUTION

### LINKED ISSUE #1027: Suggestion: provide a stable ABI for GRDB
### What did you do?

I upgraded Xcode.

### What did you expect to happen?

I expected my projects that use my binary build of the GRDB framework to compile.

### What happened instead?

Xcode complains that GRDB was built with an older version of the Swift compiler and needs to be rebuilt.

This is a common annoyance with Swift-based binary frameworks. I think the solution basically comes down to updating GRDB so that it builds with the "Build Libraries for Distribution" Xcode build option. If only it were that easy...

When I tried building GRDB with that option, I got stumped by a compiler error—probably the first of many. The fact is, writing code that allows for a stable ABI is not entirely trivial. This mode introduces some additional restrictions in Swift coding semantics. For example, ABI-stable Swift structs are more restrictive in their implementation.

In fact, I wouldn't even say that the idea of any or every Swift framework providing a stable ABI should be considered desirable for its own sake. For example, some Swift frameworks such as the gRPC integration have no intention of providing ABI stability because (I presume) it's based on code generation. However, I do think ABI stability for GRDB is worthwhile and desirable because

 * GRDB provides API stability via the semantic versioning paradigm
 * adding GRDB as a Swift source package implies compiling it every time you clean your project's build directory, and building GRDB is slow
 * other things I'm not thinking of right now

What do you think? Is this a worthwhile goal?

Thank you as always.

### Environment

**GRDB flavor(s):** GRDB with custom SQLite build
**GRDB version:** 5.8.0
**Installation method:** manual framework built with Xcode
**Xcode version:** 13.0 beta 4
**Swift version:** 5.5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.5

### PR DESCRIPTION
**Pull request by groue**
This pull requests has GRDB build with the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag.

**It does not in any way promises ABI stability.** GRDB ABI may change between two minor releases.

Fix #1027, #979, #964

cc @asifmohd, @byohay, @mallman,  @nominalista, @PratikThakareIos: would you please check if this change fits your needs? Please report your troubles building GRDB, but also new warnings or errors in your dependent projects.

Considering your feedback might take time, because such checks are not exactly a trivial task, and August is a quiet month, this PR will be merged anyway. We'll fix remaining issues later.

### CODE REVIEW

**Comment by asifmohd** [comment]
>  would you please check if this change fits your needs?

Able to create xcframeworks of GRDB now, without any issues using Xcode 12.5.1. Thanks a lot for picking this up and resolving this @groue 🙇

**Comment by groue** [comment]
Thanks @asifmohd 😉

**Comment by groue** [comment]
Shipped in v5.10.0

**Comment by mallman** [comment]
@groue, do you think the removal of the inline-related annotations will affect performance? Do you have performance regression tests?

**Comment by groue** [comment]
> Do you think the removal of the inline-related annotations will affect performance? Do you have performance regression tests?

The performance tests that help generating https://github.com/groue/GRDB.swift/wiki/Performance were not affected in any significant way. One of them was actually slightly improved, I don't remember which one, due to the enhanced decoding of low-level types such as Int, Double, or String. The compiler can jump straight to specific [C decoding functions](https://www.sqlite.org/c3ref/column_blob.html) without involving any protocol witness and other Swift dynamic trampolines :-)

I'm not able to spot all performance regressions, though (such as the infamous #983), so please report any oddity you can spot :-)

If you notice an unwanted compiler warning due to a missing `@frozen enum`, please report it as well.

**Comment by groue** [comment]
@mallman, re-reading my previous message, I notice that maybe I did not run the performance tests with explicit `BUILD_LIBRARY_FOR_DISTRIBUTION` flag on 5.10.0. So here are some fresh figures, with 5.9.0 as a baseline. Again, I do not see anything significant difference:

<details>
    <summary>GRDB 5.9.0</summary>

|                                  |      |
|:-------------------------------- | ----:|
| **Column indexes**               |      |
| Fetch                            | 0.05 |
| Insert                           | 0.05 |
| **Column names**                 |      |
| Fetch                            | 0.10 |
| Insert                           | 0.08 |
| **Records**                      |      |
| Fetch                            | 0.11 |
| Insert                           | 0.22 |
| **Codable Records**              |      |
| Fetch                            | 0.20 |
| Insert                           | 0.22 |
| **Optimized Records**            |      |
| Fetch                            | 0.06 |
| Insert                           | 0.06 |
| **Records with change tracking** |      |
| Fetch                            | 0.22 |
| Insert                           | 0.25 |


</details>

<details>
    <summary>GRDB 5.10.0 with <tt>BUILD_LIBRARY_FOR_DISTRIBUTION</tt> set in GRDB.xcodeproj</summary>

|                                  |      |
|:-------------------------------- | ----:|
| **Column indexes**               |      |
| Fetch                            | 0.07 |
| Insert                           | 0.05 |
| **Column names**                 |      |
| Fetch                            | 0.12 |
| Insert                           | 0.09 |
| **Records**                      |      |
| Fetch                            | 0.13 |
| Insert                           | 0.17 |
| **Codable Records**              |      |
| Fetch                            | 0.23 |
| Insert                           | 0.22 |
| **Optimized Records**            |      |
| Fetch                            | 0.08 |
| Insert                           | 0.05 |
| **Records with change tracking** |      |
| Fetch                            | 0.25 |
| Insert                           | 0.19 |

</details>

Those report were generated on a iMac (Retina 5K, 27-inch, 2017), with Xcode 12.5.1, by running the following command, and editing the output:

```sh
make test_performance | Tests/parsePerformanceTests.rb | Tests/generatePerformanceReport.rb
```

**Comment by mallman** [comment]
Hi @groue. The difference in performance results you posted above between 5.9 and 5.10 look significant to me, but I may be misinterpreting them. I will spend some time educating myself and report back with a more informed opinion.

**Comment by mallman** [comment]
I did a quick initial run of `make test_performance` on v5.9.0 to get started and saw about a dozen errors of the form

```
BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked
while in use: /private/var/folders/1d/3bm2td7j3zs2rsfl4y05b0xr0000gn/T/GRDBPerformanceTests-75C6FBBF-C488-4AA7-9F7F-9870DCEACDC5-16774-0001C0BC54CD8D2D.sqlite
```

logged to the console. Do you know what's behind these?

**Comment by groue** [comment]
> The difference in performance results you posted above between 5.9 and 5.10 look significant to me, but I may be misinterpreting them.

Subsequents runs of XCTest `measure` can vary, so I'm used to look at them with a grain of salt.

See the output of a few runs below, where I marked with 🔀 the lines that exhibit variations ≥ 10%:

|                                  |      |      |      |      |      |      |
|:-------------------------------- | ----:| ----:| ----:| ----:| ----:| ----:|
| **Column indexes**               |      |      |      |      |      |      |
| 🔀 Fetch                            | 0.08 | **0.07** | 0.08 | 0.07 | **0.10** | 0.07 |
| Insert                           | 0.07 | 0.07 | 0.07 | 0.07 | 0.07 | 0.07 |
| **Column names**                 |      |      |      |      |      |      |
| Fetch                            | 0.13 | 0.13 | 0.13 | 0.13 | 0.13 | 0.13 |
| Insert                           | 0.10 | 0.10 | 0.10 | 0.10 | 0.10 | 0.10 |
| **Records**                      |      |      |      |      |      |      |
| 🔀 Fetch                            | 0.13 | 0.13 | **0.14** | 0.14 | 0.14 | **0.12** |
| 🔀 Insert                           | 0.20 | 0.21 | **0.22** | 0.22 | 0.22 | **0.19** |
| **Codable Records**              |      |      |      |      |      |      |
| 🔀 Fetch                            | **0.31** | 0.25 | 0.25 | 0.25 | 0.26 | **0.23** |
| Insert                           | 0.25 | 0.26 | **0.27** | 0.27 | 0.25 | **0.24** |
| **Optimized Records**            |      |      |      |      |      |      |
| 🔀 Fetch                            | **0.08** | 0.08 | **0.09** | 0.08 | 0.08 | 0.08 |
| 🔀 Insert                           | **0.06** | **0.07** | 0.07 | 0.07 | 0.07 | 0.06 |
| **Records with change tracking** |      |      |      |      |      |      |
| 🔀 Fetch                            | **0.33** | 0.28 | 0.29 | **0.27** | 0.28 | 0.28 |
| 🔀 Insert                           | 0.22 | **0.24** | 0.22 | 0.24 | 0.22 | **0.21** |

I used to run them multiple times and grab the best figures, so that the [performance comparison](http://github.com/groue/GRDB.swift/wiki/Performance) would be "fair". I no longer do that, and just grab one result.

> `database integrity compromised by API violation: vnode unlinked`

My understanding of this message is that the database file is deleted before the connection closes. Some tests perform cleanup too early. I also see those message sometimes, and was too lazy to remove them. I agree this is not the best experience.

**Comment by groue** [comment]
> To be honest with you, I'm not quite sure my way to test BUILD_LIBRARY_FOR_DISTRIBUTION performance above has any relevance.

Well, I have some evidence that the compiler actually specializes decoding of basic scalar types, because I profiled tests with Instruments. Both 18e9b1b9aa5b557ee19bcf3af61a596548712500 and e2c9734df12076fbe579f76265f01eb090b6ae86 had an actual impact, and were necessary in order to preserve pre-5.10.0 overall performance.

**Comment by barakwei** [comment]
Hi @groue - Thanks for this truly amazing work!
Since ABI stability is not guaranteed, will it be technically possible in the future to add a compiled binary XCFramework with *static* library to the releases?

**Comment by groue** [comment]
Hello @barakwei, 

it is not planned to add pre-built libraries in the releases. Support for ABI stability is not a *commitment* to ABI stability. Think of this as a *convenience* for users who want to cache their own builds. That's nothing more.

**Comment by barakwei** [comment]
Thanks @groue for your reply
There might have been a misunderstanding on my side. To my understanding, ABI stability is relevant where you build the library and app separately and you want to replace the library without rebuilding the app. So this is relevant only when using dynamic libraries. My understanding was that for *static* libraries this is not relevant, as in any case you need to rebuild your app to use a new version.
So in theory at least, distributing a static XCframework will not require any commitment to ABI stability. It should just be "even more convenience".

**Comment by groue** [comment]
Yeah. But no. See https://github.com/groue/GRDB.swift/issues/1027

**Comment by barakwei** [comment]
I totally agree that ABI stability doesn't make any sense here.
Thanks for your time and for creating and maintaining this lib!

**Pull request merged**
