### PR TITLE
Support for Swift2.3

### PR DESCRIPTION
**Pull request by dral3x**
It's a super small change that should be integrated with no problem, I think.

### CODE REVIEW

**Comment by groue** [comment]
Please clean up your PR. Five commits for a single line change is weird.

**Comment by groue** [comment]
Sorry, hold on, don't do anything.

**Comment by groue** [comment]
A Swift 2.3 release would not only make your code run, but also the GRDBDemoiOS/watchOS app that ship with the GRDB workspace.

Unless you're willing to do this, please give up - I'll take care of it, eventually.

**Comment by groue** [comment]
Oh, I forgot: a proper release also requires testing the three installation procedures: manual, Carthage, and Cocoapods. And SQLCipher. And custom SQLite builds. On iOS, macOS, watchOS.

@dral3x, remember that the guy that answers issues is me, not you. Throwing code in is easier than maintaining a repository, and I don't want to lose time maintaining a Swift2.3 release when the future is Swift3. Please consider this PR as closed for good.

**Comment by dral3x** [comment]
I needed that fix in order to be able to ship our app compiled for iOS10 (and moved all our code and libraries to swift 2.3 as first step).

I understand your point about testing etc and makes sense. I will do it because this library needs to be compliant to swift 2.3 otherwise it cannot be used on swift 2.3 apps. You cannot ignore swift 2.3, as simple as that.
The fix is so minimal that, from my point of view, no big discussion (like this one) is needed.

I thought you appreciate at least the effort I put to test the library and fix the issue in the code.
I will made a proper PR as you asked.

Please make a Contribution guide in the repo so anyone can easily find what it's requires for ensuring the PR is accepted.

Thanks @groue

**Comment by groue** [comment]
> I needed that fix in order to be able to ship our app compiled for iOS10 (and moved all our code and libraries to swift 2.3 as first step).

I understand.

> You cannot ignore swift 2.3, as simple as that.

Oh, come on :-) Yes, I can: I'll send people asking for Swift 2.3 to https://github.com/spreaker/GRDB.swift/tree/swift2.3.
 
> The fix is so minimal that, from my point of view, no big discussion (like this one) is needed.

You don't understand what maintaining a repo is. It's not accepting innocuous-looking PR. It's committing to answering questions in the long run. Test. Setup. Try to reproduce. Think. Spend time. Often lose time.

> I thought you appreciate at least the effort I put to test the library and fix the issue in the code.
I will made a proper PR as you asked.

No, don't do that!I just wrote in my previous comment that I don't plan supporting Swift 2.3: I'm not waiting for any further PR!

> Please make a Contribution guide in the repo so anyone can easily find what it's requires for ensuring the PR is accepted.

That's not fair of you. Don't work on a PR until you have asked a repository's author if he/she's interested. You did not get a favorable answer in your initial issue #84, do you remember?

**Comment by dral3x** [comment]
> No, don't do that!I just wrote in my previous comment that I don't plan supporting Swift 2.3: I'm not waiting for any further PR!

We have a different approach about how to maintain a public open source library. GRDB is your library so it's your choice how to do it. I'll step back.

> You did not get a favorable answer in your initial issue #84, do you remember?

The issue #84 was addressed and fixed in my fork thanks to your responses and knowledge about GRDB. That was totally fine because I was using a "preview/beta" software so it shouldn't be merged in a public stable release. The fix for swift 2.3 simply could, so I made a PR.

Sorry for all this mess, it wasn't in my intentions.
Take care

**Comment by groue** [comment]
There we go: version 0.81.0 is out, with Swift 2.3 support.

**Pull request closed without merging**
