### PR TITLE
Common Table Expressions

### PR DESCRIPTION
**Pull request by groue**
This pull request brings support for [Common Table Expressions](https://sqlite.org/lang_with.html).

They were requested by at least one user: https://forums.swift.org/t/using-ctes-with-clause/39327/9

It looks like CTE could provide:
- a solution to #871: #885
- the foundations for another feature request (#856) 
- a path to a successful completion of #767

▶️ The documentation for the upcoming feature is available at https://github.com/groue/GRDB.swift/blob/dev/cte/Documentation/CommonTableExpressions.md

cc @rpoelstra

### CODE REVIEW

**Comment by rpoelstra** [comment]
Hi,

I'm trying to convert the following query:
```
WITH elementBB(minX,maxX,minY,maxY) AS
           (SELECT minX,maxX,minY,maxY FROM elementBoundingBox WHERE id = ?)
SELECT element.* FROM element
JOIN elementBoundingBox USING (id)
JOIN elementBB
WHERE elementBoundingBox.maxX>=elementBB.minX AND elementBoundingBox.minX<=elementBB.maxX AND elementBoundingBox.maxY>=elementBB.minY AND elementBoundingBox.minY<=elementBB.maxY
```

I'm basically filling the CTE with the bounding box of a reference row and then try to find all other rows that have a bounding box that touches the reference row.
The problem I have is how to reference the columns of the CTE in the WHERE clause. I tried the following:
```
        let elementBBCTE = CommonTableExpression<Void>(
            named: "elementBB",
            request: ElementBoundingBox.filter(key: element.id!))

        let request  = Element
            .joining(required: Element.boundingBox
                        .filter(ElementBoundingBox.Columns.maxX >= elementBBCTE.all().select(Column("minX")))
                        .filter(ElementBoundingBox.Columns.minX <= elementBBCTE.all().select(Column("maxX")))
                        .filter(ElementBoundingBox.Columns.maxY >= elementBBCTE.all().select(Column("minY")))
                        .filter(ElementBoundingBox.Columns.minY <= elementBBCTE.all().select(Column("maxY")))
            )
            .with(elementBBCTE)
```

But this results in the following:
```
WITH "elementBB" AS (SELECT "id", "minX", "maxX", "minY", "maxY" FROM "elementBoundingBox" WHERE "rowid" = 153) SELECT "element".*
 FROM "element" 
JOIN "elementBoundingBox" ON ("elementBoundingBox"."rowid" = "element"."id") AND ("elementBoundingBox"."maxX" >= (SELECT "minX" FROM "elementBB")) AND ("elementBoundingBox"."minX" <= (SELECT "maxX" FROM "elementBB")) AND ("elementBoundingBox"."maxY" >= (SELECT "minY" FROM "elementBB")) AND ("elementBoundingBox"."minY" <= (SELECT "maxY" FROM "elementBB"))
```
This seems less efficient to me, although it does seem to give the correct result.
Is there a way to use the CTE's columns directly in the WHERE clause?

**Comment by groue** [comment]
Hello @rpoelstra,

> I'm trying to convert the following query:
> 
> ```sql
> WITH elementBB(minX,maxX,minY,maxY) AS
>   (SELECT minX,maxX,minY,maxY FROM elementBoundingBox WHERE id = ?)
> SELECT element.* FROM element
> JOIN elementBoundingBox USING (id)
> JOIN elementBB
> WHERE elementBoundingBox.maxX>=elementBB.minX 
>   AND elementBoundingBox.minX<=elementBB.maxX 
>   AND elementBoundingBox.maxY>=elementBB.minY 
>   AND elementBoundingBox.minY<=elementBB.maxY
> ```

OK, let's do exactly this.

Setup: the `element` table is represented by `Element` record type, `elementBoundingBox` by `ElementBoundingBox`, and you have defined an association `Element.boundingBox` in between.

Your definition of the CTE is correct, although you might want to only select the columns you want, for increased fidelity to your target query:

```swift
// WITH elementBB AS
//   (SELECT minX,maxX,minY,maxY FROM elementBoundingBox WHERE id = ?)
let elementBBCTE = CommonTableExpression<Void>(
    named: "elementBB",
    request: ElementBoundingBox
        .select(["minX", "maxX", "minY", "maxY"].map(Column.init(_:)))
        .filter(key: element.id!))
```

The target query contains two joins. GRDB generates joins when you use the `joining(required:)` method, with an association as its argument ([doc](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#joining-and-prefetching-associated-records)).

You already have `Element.boundingBox` that handles `JOIN elementBoundingBox USING (id)`:

```swift
// SELECT element.* FROM element
// JOIN elementBoundingBox ON (foreign key condition)
Element
    .joining(required: Element.boundingBox)
```

You need another association to the CTE for `JOIN elementBB` ([doc](https://github.com/groue/GRDB.swift/blob/dev/cte/Documentation/CommonTableExpressions.md#associations-to-common-table-expressions)):

```swift
let elementBB = Element.association(to: elementBBCTE)

// WITH elementBB AS
//   (SELECT minX,maxX,minY,maxY FROM elementBoundingBox WHERE id = ?)
// SELECT element.* FROM element
// JOIN elementBoundingBox ON (foreign key condition)
// JOIN elementBB
Element
    .with(elementBBCTE)
    .joining(required: Element.boundingBox)
    .joining(required: elementBB)
```

Now let's deal with the `WHERE` clause.

When a condition that involves a joined table is expressed in the `WHERE` clause instead of the `ON` clause of the join, you need a `TableAlias` ([doc](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#table-aliases)):

```swift
let elementBoundingBoxAlias = TableAlias()
let elementBBAlias = TableAlias()
let elementBB = Element.association(to: elementBBCTE)

// WITH elementBB AS
//   (SELECT minX,maxX,minY,maxY FROM elementBoundingBox WHERE id = ?)
// SELECT element.* FROM element
// JOIN elementBoundingBox ON (foreign key condition)
// JOIN elementBB
// WHERE elementBoundingBox.maxX>=elementBB.minX 
//   AND elementBoundingBox.minX<=elementBB.maxX 
//   AND elementBoundingBox.maxY>=elementBB.minY 
//   AND elementBoundingBox.minY<=elementBB.maxY
Element
    .with(elementBBCTE)
    .joining(required: Element.boundingBox.aliased(elementBoundingBoxAlias))
    .joining(required: elementBB.aliased(elementBBAlias))
    .filter([
        elementBoundingBoxAlias[Column("maxX")] >= elementBBAlias[Column("minX")], 
        elementBoundingBoxAlias[Column("minX")] <= elementBBAlias[Column("maxX")], 
        elementBoundingBoxAlias[Column("maxY")] >= elementBBAlias[Column("minY")], 
        elementBoundingBoxAlias[Column("minY")] <= elementBBAlias[Column("maxY")],
        ].joined(operator: .and))
```

**Comment by groue** [comment]
I'm sure CTE support can be improved, but I'm also reasonably confident that we have a robust base. CTE will ship as an experimental feature (meaning I'll be able to introduce breaking changes if a flaw appears).

**Comment by rpoelstra** [comment]
I was just processing your elaborate explanation.
I'm sure it's a robust base indeed, it's just my lack of understanding here :)
What enlightens me is the notion that `TableAlias` doesn't need to know anything about the columns of the table, which I thought it would get from the Columns definition of a record. This confused me, as the CTE didn't have the columns so I didn't know I could use the alias trick.
Thanks for the support.

**Comment by groue** [comment]
> I was just processing your elaborate explanation.
> I'm sure it's a robust base indeed, it's just my lack of understanding here :)

I'm quite listening, because a lack of understanding reveals a lack of the documentation!

> What enlightens me is the notion that `TableAlias` doesn't need to know anything about the columns of the table, which I thought it would get from the Columns definition of a record. This confused me, as the CTE didn't have the columns so I didn't know I could use the alias trick.

Hm. Yeah, table aliases are, in a way, just references to other tables.

They exist for a reason:

For simplicity's sake, all expressions in GRDB requests refer to an implicit table:

```swift
// SELECT * FROM player WHERE score > 1000
let request = Player.filter(Column("score") > 1000)
//                          ~~~~~~~~~~~~~~~
//                          implicit table player
```

These implicit scoping of expressions also applies to requests that involve several tables:

```swift
// SELECT player.*, team.*
// FROM player
// JOIN team ON team.id = player.teamID
//           AND team.color = 'red'
// WHERE player.score > 1000
// ORDER BY player.name
let request = Player
    .filter(Column("score") > 1000) // implicit table player
    .order(Column("name"))          // implicit table player
    .including(required: Player.team
                               .filter(Column("color") == "red")) // implicit table team
```

But now we have a problem: sometimes we need to build expressions that mix columns from various sources.

And that's what `TableAlias` is for! See below:

```swift
// SELECT player.*, team.*
// FROM player
// JOIN team ON team.id = player.teamID
// WHERE player.score >= team.minimumScore
let teamAlias = TableAlias()
let request = Player
    .including(required: Player.team.aliased(teamAlias))
    .filter(Column("score") >= teamAlias[Column("minimumScore")])
//          ~~~~~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//    implicit table player    explicit reference to the joined team table
```

Now, CTEs reuse existing GRDB concepts: requests and associations. That's how they inherit support for multiple joins, filtering of joins, subqueries, table aliases (when a column needs to escape the implicit scoping), etc.

Eventually, we have an API which is *verbose* :-/ But it is very flexible. And experience may help us streamline some frequent use cases eventually.

**Comment by rpoelstra** [comment]
Thanks for the additional explanation. That makes things a lot clearer.

I'm working on converting my last CTE to the new request query API, but I think I'm (again :( ) a bit stuck.
I don't think this is a CTE problem, but more an `UPDATE` problem:
```
WITH parentInfo(parentId, maxSibling) AS (SELECT parentId, MAX(sibling) FROM element WHERE parentId = (SELECT parentId FROM element WHERE id = ?))
UPDATE element SET (parentId, sibling) = (SELECT parentId, maxSibling+1+sibling FROM parentInfo) WHERE parentId = ?
```

Building the CTE is quite easy:
```
let parentIdRequest = Element.select(Element.Columns.parentId).filter(key: element)
let parentInfoCTE = CommonTableExpression<Void>(
    named: "parentInfo",
    columns: ["parentId", "maxSibling"],
    request: Element
         .select(Element.Columns.parentId)
         .annotated(with: max(Element.Columns.sibling))
         .filter(Element.Columns.parentId == parentIdRequest)
)
```

But now the problem is the `UPDATE` query. It wants column assignments, but I want to execute a subquery :)
The best I could come up with was:
```
 _ = try! Element
    .filter(Element.Columns.parentId == element)
    .updateAll(db, [Element.Columns.parentId.set(to: parentInfoCTE.all().with(parentInfoCTE).select(Column("parentId"))),
                    Element.Columns.sibling.set(to: parentInfoCTE.all().with(parentInfoCTE).select(Column("parentId"))+1+Element.Columns.sibling)
      ])
```

But this will (of course) execute the `WITH` clause twice.
Is there a way to use the subquery syntax for `UPDATE`?

**Comment by groue** [comment]
This pull request has no support for CTEs in UPDATE statements yet!

**Comment by rpoelstra** [comment]
I already had a suspicion, but wanted to make sure I hadn’t missed the obvious.

**Comment by groue** [comment]
Actually I did not think about this 😅

If it's easy to deal with your sample query, this will be included in this PR as well.

Anyway, thank your very much for sharing your needs and experience 👍

**Comment by groue** [comment]
> If it's easy to deal with your sample query, this will be included in this PR as well.

It was quite easy :-) Thanks for the suggestion!

**Comment by groue** [comment]
> ```
> UPDATE element SET (parentId, sibling) = (
> ```

GRDB has no public support for row values. The `set(to:)` method is only available for columns, currently.

**Comment by groue** [comment]
> > ```
> > UPDATE element SET (parentId, sibling) = (...)
> > ```
> 
> 
> GRDB has no public support for [row values](https://www.sqlite.org/rowvalue.html). The `set(to:)` method is only available for columns, currently.

Experimental support for this is brought by #890.

**Pull request merged**
