### PR TITLE
Added differentiation on iOS and OSX sqlite module

### PR DESCRIPTION
**Pull request by morisk**
Module was causing conflicts with OSX version, running from IOS perspective. I've split to two different module files.
IOS 
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h`

OSX
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sqlite3.h`

And for Xcode betas its simple by replacing
Xcode -> Xcode-beta

### CODE REVIEW

**Comment by morisk** [comment]
Nope, sorry i thought i fixed it. When using iPhone it went fine. In simulator Xcode complains again

**Comment by groue** [comment]
Module files are tricky beasts, aren't they? Xcode 7.3 and Swift 2.2 may bring their own set of beta oddities. I won't merge any pull request on beta software, because I want the master branch to work on the latest stable tools. Still I'm glad to share experience with you, because people that run betas need help as well.

**Comment by groue** [comment]
Please bring your eventual future comments in https://github.com/groue/GRDB.swift/issues/24

**Comment by morisk** [comment]
That fix intenteded to stabe xcode. Actually i dont understand why it doesnt conflict in stable xcode. 
You declare path to osx sdk on ios build. 

But yea most likely you right, never trust betas :)

**Comment by groue** [comment]
@morisk: the [Swift 2.2 branch](https://github.com/groue/GRDB.swift/tree/Swift2.2) should avoid this kind of issues now ([relevant commit](https://github.com/groue/GRDB.swift/commit/c6f96906caa2fe0619097fac76abbfcdbf9ad2da)).

**Comment by groue** [comment]
Actually I think your PR was superior, because it did not imply changes in the source files that use SQLite C API... OK I'm sorry I overlooked your contribution. It will come back. Thank you for your investigations!

**Comment by morisk** [comment]
I am not sure its better, need to look at it further.

**Comment by groue** [comment]
After a second thought, I'm in doubt as well: in the current beta (Xcode 7.3 beta 5), we need a different header when we're compiling for an iOS simulator or for a device. A target-based differentiation is not enough.

**Comment by groue** [comment]
I don't even know if those are beta issues or features :wink:

**Pull request closed without merging**
