### PR TITLE
Docs: Fix a collection of typos

### PR DESCRIPTION
**Pull request by haikusw**
Just cleans up some small typos in various documentation files (did a spell check to find ones I noticed while reading docs last night plus any others I hadn't seen yet).

### CODE REVIEW

**Comment by groue** [comment]
Thank you very much @haikusw, for this PR, and the kind notice that it's high time I systematically used a spell checker myself 😅

**Comment by haikusw** [comment]
_Please_ don't take my spell checker comment as any kind of "notice" or critique!  I only mentioned the spell check to make it clear that I didn't do the more thorough read through carefully looking for correctly spelled but incorrect word kind of issues.

As I said, I had noticed some minor typos while reading parts of the documentation the night before and the easiest way for me to find them again the next day was with a spell checker.

You have provided extensive and quite good documentation - which is often missing from open source projects - and I have only feelings of appreciation and gratitude towards you for doing so.  It is that feeling of gratitude that prompted me to make the effort to help out, not some fussy 'this must be perfect!' critical perspective.

Thank you for your work on GRDB and related and for providing extensive documentation!

**Comment by groue** [comment]
Don't worry, your contribution was warmly welcomed! I'm not an English native, so I'm not good at spotting my mistakes, or the weirdness of some sentences. To me, documentation is just as important as features, and I do really appreciate this kind of (rare) contribution :-) Now, I should really learn how to use a spell checker 😅

**Comment by haikusw** [comment]
Your English is 7,000x better than any pitiful remnants that might remain of my 30-years-ago three-years-of-high-school French!  So don't sweat the any minor mistakes. English is weird anyway (!).  The spell checker I used is the one built into BBEdit (Edit > Spelling > …) because that's what I am currently using to edit markdown files.  You might need to add English as a supported language in the "System Preferences…"  "Language & Region" pane "General" tab.  Looks like BBEdit lets you choose the language to spell check by showing the spelling pane (Edit > Spelling > Show Spelling Pane") which lets you choose at the bottom which language to use for spell-checking.

**Pull request merged**
