### PR TITLE
Add coalesce free function and Row method

### PR DESCRIPTION
**Pull request by philmitchell**
As [discussed](https://github.com/groue/GRDB.swift/issues/1632) with @groue, added `coalesce` methods as a best-effort alternative in cases where nil-coalescing fails. (I did investigate addressing the failure directly, but given the double optionals that represent null values (`.some(.none)`), it seems unlikely to bear fruit.)

### Pull Request Checklist

- [x] CONTRIBUTING: You have read https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md
- [x] BRANCH: This pull request is submitted against the `development` branch.
- [x] DOCUMENTATION: Inline documentation has been updated.
- [x] DOCUMENTATION: README.md or another dedicated guide has been updated.
- [x] TESTS: Changes are tested.
- [x] TESTS: The `make smokeTest` terminal command runs without failure.

### CODE REVIEW

**Comment by groue** [comment]
Hello @philmitchell, I'm glad to hear about you :) Please give me a couple of days before I can review the pull request.

**Comment by groue** [comment]
Welcome to the GRDB contributors, @philmitchell!

I added a few commits, and we're going to be able to merge :-)

**Comment by groue** [comment]
⛵ Shipped in 7.0.0-beta.3

**Comment by philmitchell** [comment]
Thanks, @groue, it's really a privilege! Sorry about all the cleanup you had to do, I will never be offended if you reject a PR w/ suggestions :)

Hopefully we will figure out something around [GRDB 7 and SQLCipher](https://github.com/groue/GRDB.swift/discussions/1495) so that I can actually use this!

**Comment by groue** [comment]
You're very welcome, because coalesce addresses a real need! 😄 I was looking forward to merge, so I made a few changes on the go.

> Hopefully we will figure out something around [GRDB 7 and SQLCipher](https://github.com/groue/GRDB.swift/discussions/1495) so that I can actually use this!

Yes, that's a big topic. Last year's development efforts have been absorbed by Swift Concurrency. I hope the path is now cleared for other topics, such as SQLCipher.

**Pull request merged**
