### PR TITLE
Prohibit observation of tables created WITHOUT ROWID

### PR DESCRIPTION
**Pull request by simme**
As discussed in #945 this PR adds a fatal error whenever a developer attempts to observe a table that lacks a rowid. Since SQLite does not report changes to these tables, notifying the developer of this makes sense.

The method on `DatabaseRegion` that performs the check loops all table regions and checks if those tables have a `rowid` and returns the names of tables that don't. First I had a variant that returned a `bool` as soon as a table without `rowid` was found. Thinking we don't need to check more than that. But it struck me that for valid regions the loop will always check every table anyway. So it felt better to instead gather up the names of the offending tables, if more than one, to provide better error reporting to the user.

I am not 100% confident that the single test case covers all bases.

I have not updated the README as I think maybe the documentation as is probably is enough together with this change.

And of course, let me know if you're not happy with the solution. You probably know if there are better ways to do it :)

### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested. **Two other tests in the suite failed, but they seemed unrelated to this change**

### CODE REVIEW

**Comment by groue** [comment]
Thank you @simme!

> So it felt better to instead gather up the names of the offending tables, if more than one, to provide better error reporting to the user.

I very much agree!

> I am not 100% confident that the single test case covers all bases.

It looks quite good to me.

> I have not updated the README as I think maybe the documentation as is probably is enough together with this change.

Yes. I can take care of it.

> Two other tests in the suite failed, but they seemed unrelated to this change

They do not fail without the new check in `ValueObserver`, so they are (indirectly) related ;-) Do you feel like investigating? I'll provide help if needed. And if you don't have time, I'll complete this excellent pull request.

**Comment by groue** [comment]
Would you please allow me to push to your branch?

**Comment by groue** [comment]
Thanks ;-)

**Comment by simme** [comment]
> They do not fail without the new check in ValueObserver, so they are (indirectly) related ;-) Do you feel like investigating? I'll provide help if needed. And if you don't have time, I'll complete this excellent pull request.

Oh. Could've sworn I ran the tests without my changes and got the same. Will double check.

> Would you please allow me to push to your branch?

✅

---

I'll be able to look more on this tomorrow.

**Comment by simme** [comment]
I've tried a few different things. My conclusion is that the `testWriteObservation()` test fails with `caught error: "SQLite error 1: no such table: temp"`. Commenting these lines in my new method makes the test pass.
```swift
let pkInfo = try db.primaryKey(table)
if !pkInfo.tableHasRowID {
  tables.append(table)
}
```.

I think I'm lacking a little bit of insight into how SQLite works in this case.

This is the observation in the test:
```swift
var observation = ValueObservation.trackingConstantRegion { db -> Int in
    XCTAssert(db.isInsideTransaction, "expected a wrapping transaction")
    try db.execute(sql: "CREATE TEMPORARY TABLE temp AS SELECT * FROM t")
    let result = try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM temp")!
    try db.execute(sql: "DROP TABLE temp")
    return result
}
```

Could it be something with the accessing of the database when checking the primary keys on a table that somehow makes the temporary table disappear?

**Comment by groue** [comment]
This test makes sure users can define observations that write (#42). I don't remember why I put a temporary table there. But I'm happy I did :-)

When I run this test with a breakpoint on all Swift errors, I can see that since the observed region contains both the `temp` and `t` tables, the new code attempts at making sure none of them is WITHOUT ROWID, and loads the primary key for the "temp" table. `Database.primaryKey(_:)` calls `Database.columns(in:)`, which does not support temp tables: it throws "no such table" instead.

Capture d’écran 2021-03-24 à 10 01 33

One can wonder if it is useful to track [temporary tables](https://www.sqlite.org/tempfiles.html#temp_databases) as all:

> Tables created using the "CREATE TEMP TABLE" syntax are only visible to the database connection in which the "CREATE TEMP TABLE" statement is originally evaluated.

Since `DatabasePool` has ValueObservation fetch from one unspecified reader connection from its pool, it's impossible to guarantee that it will see a temp table...

But `DatabaseQueue` and `ValueObservation` with the `requiresWriteAccess` can do it (since both have the observation fetch from the single writer connection)...

A possible fix is to have `Database.primaryKey(_:)` able to run on temp tables. According to https://sqlite-users.sqlite.narkive.com/QOXQJwBh/accessing-temporary-tables, we need to prefix the table name with 'temp' when we run the `table_info` and `table_xinfo` pragmas.

I can't make up my mind right now. I'll come back. Your ideas are of course welcomed.

**Comment by simme** [comment]
If it's fairly straight forward to detect a temporary table and if so update `Database.primaryKey(_:)` to work on them that seems like the correct fix. But the whole use case do seem very edge-casey, might be a balance where the extra overhead and maintenance cost is not worth it?

That said, I don't know what's right 🤷🏼‍♂️

**Comment by groue** [comment]
Yes, I was having a look, and starting to think that cleaning up the way GRDB handles [schemas](https://sqlite.org/lang_naming.html) first (the default "main", the built-in "temp", and custom ones with attached databases) should be done first.

**Comment by groue** [comment]
@simme, here is a temporary conclusion:

- we do not merge this pull request today
- I update the doc so that users understand that WITHOUT ROWID tables are not tracked

And we'll revive this pull request in the future, if we're ready and still think it's worth it.

Is it OK for you?

**Comment by simme** [comment]
Yep, absolutely!
My initial issue was fixed by not using WITHOUT ROWID, which was a pre-mature optimization that I thought would simplify things. Let me know if there's anything else I can do to be of assistance :)

**Comment by groue** [comment]
I'm happy we could explore a little bit a new topic! Thanks for the short but enjoyable journey, @simme. See you soon, happy GRDB!

**Pull request closed without merging**
