### PR TITLE
Fix creation of FTS5 tokenizer with arguments

### LINKED ISSUE #900: Failed to create wrapped tokenizer with multiple arguments
### What did you do?

Using FTS5 with custom tokenizer like this:

```Swift
class Tokenizer: FTS5WrapperTokenizer {
    
    static let name = "test"
    
    let wrappedTokenizer: FTS5Tokenizer
    
    required init(db: Database, arguments: [String]) throws {
        wrappedTokenizer = try db.makeTokenizer(.unicode61(diacritics: .removeLegacy, separators: ["-", "_"]))
    }
    
    func accept(token: String, flags: FTS5TokenFlags, for tokenization: FTS5Tokenization, tokenCallback: (String, FTS5TokenFlags) throws -> Void) throws {
        try tokenCallback(token, [])
    }
    
}
```

### What did you expect to happen?

Running without error

### What happened instead?

```
SQLite error 1: error in tokenizer constructor - while executing `CREATE VIRTUAL TABLE "foo_fts" USING fts5(a, tokenize='test')`
```

#### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

#### Podfile

```ruby
install! 'cocoapods',
:generate_multiple_pod_projects => true

platform :ios, '12.0'

target 'FTS5TokenizerDemo' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher', '~> 4.4.2'
end
```

### Researches

I tried to do some research by myself. The SQLITE_ERROR is thrown from `fts5UnicodeCreate`, which gets called when GRDB  initialize a unicode61 tokenizer. It checks if `nArg%2` in the beginning, to ensure the arguments are in pairs. When a tokenizer is created with `.unicode61(diacritics: .removeLegacy, separators: ["-", "_"])`, sqlite receives an nArg of 1, which prevents unicode61 tokenizer from creation.

Somehow I managed to make it work by modifying init of FTS5RegisteredTokenizer, to create the tokenizer like this:
```Swift
let cargs = ContiguousArray(arguments.map({ strdup($0) }))
code = cargs.withUnsafeBufferPointer { azArg in
    xCreate(
        contextPointer,
        UnsafeMutablePointer(OpaquePointer(azArg.baseAddress!)),
        Int32(cargs.count),
        &tokenizerPointer)
}
cargs.forEach({ free($0) })
```

Here's the comparison from my fork:
https://github.com/groue/GRDB.swift/compare/master...wuyuehyang:mixin

I would like to contribute by creating some pull requests, but I'm not quite familiar with porter or ascii tokenizers, don't know whether creating tokenizers like this will break them or not. Neither do I test my changes with FTS5TokenizerTests, it runs only when SQLITE_ENABLE_FTS5 is defined. I think maybe I should test it with a custom SQLite build? But I didn't find any guide about testing with FTS5.

### Demo project

[FTS5TokenizerDemo.zip](https://github.com/groue/GRDB.swift/files/5740238/FTS5TokenizerDemo.zip)

### PR DESCRIPTION
**Pull request by wuyuehyang**
This PR fixes #900 

All changes are made in a private class, so no documentation needs to be updated.

The corresponding test case is committed independently before the patch commit, so you can test it before/after the fix.

### Pull Request Checklist

- [x] This pull request is submitted against the `development` branch.
- [x] Inline documentation has been updated.
- [x] README.md or another dedicated guide has been updated.
- [x] Changes are tested.

### CODE REVIEW

**Comment by groue** [comment]
This looks like a perfect pull request, @wuyuehyang, thank you very much!

It looks that there were a shorter fix, by moving [this line](https://github.com/groue/GRDB.swift/blob/v5.2.0/GRDB/FTS/FTS5Tokenizer.swift#L168) up, above the `if`. But I like your version more. Iterative and simple 👍 

Would you accept an invitation that grants you a push access to GRDB? I do intend to keep the lead of the project, but it is good for everyone that people of various levels of Swift and SQLite expertise can act on the repository when it becomes necessary: you'll be very welcome!

**Comment by wuyuehyang** [comment]
Thanks for your appreciation, @groue .
Actually we're managed to use GRDB in our product, it's my responsibility to contribute back.
I'll try my best to do some work, but maybe not that responsive, I still have a full time job to do. So feel free to remove me at any time😁

**Comment by groue** [comment]
> Thanks for your appreciation, @groue .
> Actually we're managed to use GRDB in our product, it's my responsibility to contribute back.
> I'll try my best to do some work, but maybe not that responsive, I still have a full time job to do. So feel free to remove me at any time😁

Feel no obligation! This is an open source project, fed on our free time, our needs, and our pleasure, and I firmly want it to remain so, for the benefit of all! Welcome, and thanks again for your contribution :-)

Happy GRDB!

**Comment by groue** [comment]
Shipped in v5.3.0

**Pull request merged**
